name: Validate Changes

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli --global

    - name: Authenticate with Salesforce
      env:
        SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
      run: |
        echo $SFDX_AUTH_URL > sfdx-auth-url.txt
        sfdx force:auth:sfdxurl:store -f sfdx-auth-url.txt -a ProdOrg

    - name: Read test classes from file
      id: read_test_classes
      run: |
        TEST_CLASSES=$(cat test-classes.txt | tr '\n' ',' | sed 's/,$//')
        echo "::set-output name=test_classes::$TEST_CLASSES"

    - name: Validate deployment
      run: |
        set -e
        sfdx force:source:deploy -u ProdOrg -p force-app/main/default --checkonly --testlevel RunSpecifiedTests --runtests ${{ steps.read_test_classes.outputs.test_classes }}

    - name: Cleanup
      if: always()
      run: |
        echo "Cleaning up orphan processes"
        pkill -P $$
